window.GAME = {
  meta: {
    title: 'RING & WRONG',
    version: 'v0.10.0',
    storageKey: 'ringandwrong',
    subtitle: 'A thoroughly unnecessary hero\'s tale',
    tagline: 'A point-and-click adventure in the spirit of LucasArts',
    about: [
      'A point-and-click adventure in a spirit of loving parody.',
      '',
      'No hobbits were harmed during production.',
      '(Several pumpkins, however, were grossly mistreated.)',
      '',
      'Right-click: look at things. Left-click: do things.',
      'You CANNOT die. That is the entire point.',
      'Uncle Bongo wishes you a pleasant evening.',
      '',
      'Click anywhere to go back.',
    ],
  },

  ui: {
    hintRightClick: 'right-click = look / cancel',
    hintEsc: 'ESC = menu',
    leave: '( leave )',
  },

  speakers: {
    colors: {
      toke:    '#ffd94a',
      bongo:   '#7fd4ff',
      rando:   '#9be37b',
      dora:    '#ff9e64',
      halvor:  '#ff7f7f',
      grim:    '#c9a7ff',
      perr:    '#ff5555',
      bent:    '#b8b8ff',
      goblin:  '#8ee06a',
      bjarne:  '#ffb14a',
      glum:    '#aef3d2',
      glumpeek:'#aef3d2',
      glumfinale:'#aef3d2',
      goblin:  '#8ee06a',
      tommel:  '#ffffff',
      narrator:'#e8e8e8',
      ring:    '#ffd700',
    },
    names: {
      toke: 'TOMBLE',
      bongo: 'UNCLE BONGO',
      rando: 'RANDO',
      dora: 'DORA',
      halvor: 'HALVOR',
      grim: 'GRIM',
      perr: 'BLACK RIDER',
      bent: 'BENT',
      goblin: 'GOBLIN',
      bjarne: 'BJARNE',
      glum: 'GLUM',
      glumpeek: 'GLUM',
      glumfinale: 'GLUM',
      tommel: 'BILLY',
      ring: 'THE RING',
      narrator: '',
    },
  },

  intro: [
    ['In an age before ages got late,',
     'the Great Rings were forged in the factories of Middle-earth.',
     'Three for the elves. Seven for the dwarves. Nine for men â€“',
     'and one to rule them all â€¦ plus the service agreement.'],
    ['But one day, the Great Ring went missing.',
     'It turned up in the pocket of UNCLE BONGO,',
     'a retired adventurer who refused to believe it was more than loose change.',
     '"Probably from a vending machine," he said. He said it often. Nervously.'],
    ['Now the Dark Lord\'s Vice-Chancellor has booked a pickup.',
     'The only one who can save the neighborhood is a small halfling',
     'with big feet and a poor sense of planning:',
     'TOMBLE BAGSHOT. That is you. Sorry.'],
  ],

  endings: {
    good: {
      title: 'THE END â€” the good kind!',
      lines: [
        'The Ring screamed "NOOO! I had SO much left to give!"',
        'and melted away with a tiny confetti-bang.',
        'The Dark Lord lost his job and opened a bakery instead.',
        'Uncle Bongo flew past on an eagle: "I TOLD you I would come!"',
        'Rando\'s first comment: "So the food at your uncle\'s WAS free, right?"',
      ],
    },
    bad: {
      title: 'THE END â€¦ or is it?',
      lines: [
        'Tomble kept the Ring. The Ring kept Tomble.',
        'Three weeks later he was middle manager at Mordor Inc.,',
        'in charge of meeting minutes and evil looks.',
        'The pay was poor. The coffee was worse.',
        'Uncle Bongo sent a card: "Regards, grandma. PS: My ring?"',
      ],
    },
  },

  difficulty: {
    levels: ['easy', 'normal', 'hard'],
    labels: { easy: 'EASY', normal: 'NORMAL', hard: 'HARD' },
    rules: {
      riddleRounds: { easy: 1, normal: 3, hard: 3 },
      hintLevel: { easy: 2, normal: 1, hard: 0 },
    },
  },
};
