const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'js', 'games', 'ring-and-wrong', 'art');
const ids = ['dal', 'kryss', 'pub', 'elv', 'skog', 'vulkan', 'krater'];
const out = [];

ids.forEach(id => {
  for (const ext of ['png', 'jpeg', 'jpg']) {
    const f = path.join(dir, id + '.' + ext);
    if (fs.existsSync(f)) {
      const b = fs.readFileSync(f);
      out.push('  ' + id + ':\n    "data:image/' + (ext === 'jpg' ? 'jpeg' : ext) + ';base64,' + b.toString('base64') + '",');
      console.log('embedded', id + '.' + ext, Math.round(b.length / 1024) + 'kB');
      return;
    }
  }
  console.log('MISSING (procedural fallback will be used):', id);
});

let js = '// AUTO-GENERATED by tools/build-art.js â€” embedded backgrounds so the game works from file://\n';
js += '// Re-run "node tools/build-art.js" after swapping images in art/\n';
js += 'window.ART_DATA = {\n' + out.join('\n') + '\n};\n';

fs.writeFileSync(path.join(__dirname, '..', 'js', 'games', 'ring-and-wrong', 'art-data.js'), js);
console.log('Wrote js/art-data.js (' + Math.round(js.length / 1024) + 'kB)');
