const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'music');
const ids = ['title', 'dal', 'kryss', 'pub', 'elv', 'skog', 'vulkan', 'krater', 'ending'];
const out = [];
let any = false;

ids.forEach(id => {
  for (const ext of ['mp3', 'ogg', 'm4a', 'wav']) {
    const f = path.join(dir, id + '.' + ext);
    if (fs.existsSync(f)) {
      const b = fs.readFileSync(f);
      const mime = ext === 'mp3' ? 'mpeg' : ext === 'm4a' ? 'mp4' : ext;
      out.push('  ' + id + ':\n    "data:audio/' + mime + ';base64,' + b.toString('base64') + '",');
      console.log('embedded', id + '.' + ext, Math.round(b.length / 1024) + 'kB');
      any = true;
      return;
    }
  }
  console.log('(no track for', id + ' - procedural music will be used)');
});

let js = '// AUTO-GENERATED by tools/build-music.js - embedded music tracks (works from file://)\n';
js += '// Re-run "node tools/build-music.js" after adding files to music/\n';
js += 'window.MUSIC_DATA = {\n' + (out.join('\n') || '  // empty\n') + '};\n';

fs.writeFileSync(path.join(__dirname, '..', 'js', 'music-data.js'), js);
console.log(any ? 'Wrote js/music-data.js (' + Math.round(js.length / 1024) + 'kB)' : 'Wrote EMPTY js/music-data.js (no tracks found)');
