const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'games', 'ring-and-wrong', 'art', 'chars');
const outPath = path.join(__dirname, '..', 'games', 'ring-and-wrong', 'chars-data.js');

if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
  console.log('No chars dir — created', dir);
}

const map = new Map(); // key -> {file, mime, b64, kb}
const files = fs.readdirSync(dir).filter(f => /\.(png|jpe?g)$/i.test(f));
files.forEach(f => {
  const full = path.join(dir, f);
  const b = fs.readFileSync(full);
  const ext = path.extname(f).slice(1).toLowerCase();
  const mime = ext === 'jpg' || ext === 'jpeg' ? 'jpeg' : ext;
  const key = path.basename(f, path.extname(f)).toLowerCase();
  const kb = Math.round(b.length / 1024);
  const cur = map.get(key);
  // prefer png over jpeg (cleaner magenta)
  if (!cur || (mime === 'png' && cur.mime !== 'png')) {
    map.set(key, { f, mime, b64: b.toString('base64'), kb });
  }
});
const out = [];
for (const [key, v] of map.entries()) {
  out.push(`  "${key}": "data:image/${v.mime};base64,${v.b64}"`);
  console.log('embedded', v.f, v.kb + 'kB ->', key, v.mime === 'png' ? '(png preferred)' : '');
}

if (!out.length) console.log('(no char sheets found in', dir, '— procedural fallback will be used)');

let js = '// AUTO-GENERATED by tools/build-chars.js — embedded char sheets so the game works from file://\n';
js += '// Re-run "node tools/build-chars.js" after adding/replacing sheets in art/chars/\n';
js += 'window.CHARS_DATA = {\n' + out.join(',\n') + (out.length ? '\n' : '') + '};\n';

fs.writeFileSync(outPath, js);
console.log('Wrote', path.relative(path.join(__dirname, '..'), outPath), '(' + Math.round(js.length / 1024) + 'kB)');
